spring.application.name=CONFIG-SERVER
server.port=8888

# ? GIT CONFIG REPO
spring.cloud.config.server.git.uri=https://github.com/sarthakpawar0912/Car-Wash-central-config-repo-.git
spring.cloud.config.server.git.clone-on-start=true

# ? IMPORTANT (avoid branch issues)
spring.cloud.config.server.git.default-label=main

# ? OPTIONAL (faster startup + no SSL issues sometimes)
spring.cloud.config.server.git.skip-ssl-validation=true

# ? EUREKA
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# ? DEBUG (optional but useful)
logging.level.org.springframework.cloud.config=DEBUG


# ? IMPORTANT
management.endpoints.web.exposure.include=*

# ? BUS (RabbitMQ)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest